config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('employee_learning.urls')),
    path('admin/', admin.site.urls),
    path('test-app/', include('test_app.urls')),
    path('employee-learning/', include('employee_learning.urls')),
    path('accounts/', include('allauth.urls')),
]

employee_learning/urls.py
from django.urls import path
from .views import CourseList, CourseDetail, CourseCreate, CourseUpdate, CourseDelete, Index




urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('course-list/', CourseList.as_view(), name='course_list'),
    path('course-detail/<int:pk>/', CourseDetail.as_view(), name='course_detail'),
    path('course-create/', CourseCreate.as_view(), name='course_create'),
    path('course-update/<int:pk>/', CourseUpdate.as_view(), name='course_update'),
    path('course-delete/<int:pk>/', CourseDelete.as_view(), name='course_delete'),
]

test_app/urls.py
from django.urls import path
from .views import function_view_test, ClassViewTest

urlpatterns = [
    path("test-function/", function_view_test),
    path("test-class/", ClassViewTest.as_view()),
]

employee_learning/models.py
from django.db import models
from django.utils.timezone import now
from phonenumber_field.modelfields import PhoneNumberField

class Division(models.Model):
    div_name = models.CharField(max_length=25, verbose_name="Division Name")
    in_scope = models.BooleanField(help_text="If the division is target for the learning program, check this field")

    class Meta:
        verbose_name = "Division"
        verbose_name_plural = "Divisions"

    def __str__(self):
        return f"{self.div_name}"


class Employee(models.Model):
    PRIORITIES = [('H', 'High'), ('M', 'Medium'), ('L', 'Low')]
    name = models.CharField(max_length=25, verbose_name='Name')
    priority = models.CharField(
        max_length=1,
        verbose_name="Learning Priorities",
        choices=PRIORITIES,
        default="M"
    )
    reg_date = models.DateField(default=now, verbose_name="Registration Date")
    division = models.ForeignKey(Division, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Employee"
        verbose_name_plural = "Employees"

    def __str__(self):
        return f"{self.name}"


class PersonalInfo(models.Model):
    name = models.OneToOneField(Employee, on_delete=models.CASCADE, primary_key=True)
    tel = PhoneNumberField(
        verbose_name="Telephone Number",
        blank=True,
        null=True,
        help_text="Enter a valid phone number (e.g. +12125552368)",
    )
    address = models.CharField(max_length=100, verbose_name="Address")

    def __str__(self):
        return f"Personal Info for {self.name}"


class LearningCourse(models.Model):
    LEVEL = [('B', 'Basic'), ('I', 'Intermediate'), ('A', 'Advanced')]
    title = models.CharField(max_length=50, verbose_name="Course Title", unique=True)
    level = models.CharField(max_length=1, verbose_name="Course Level", choices=LEVEL, default="B")
    employee = models.ManyToManyField(Employee, verbose_name="Enrolled Employees")

    class Meta:
        verbose_name = "Learning Course"
        verbose_name_plural = "Learning Courses"

    def __str__(self):
        return f"{self.title}"

test_app/models.py
from django.db import models

# Create your models here.

user_profile/models.py
"""Создание пользовательской модели"""
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    modile = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.user.username

employee_learning/forms.py
from allauth.account.forms import ResetPasswordForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django import forms

class MyForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'E-Mail',
            ),
            Fieldset(
                'Password',
            ),
            ButtonHolder(
                Submit('submit', 'Save', css_class='button white')
            )
        )

class  CustomResetPasswordForm(ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].help_text = ''

employee_learning/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView
from employee_learning.models import LearningCourse
from django.urls import reverse_lazy
from django.utils import timezone
# Create your views here.



class CourseList(LoginRequiredMixin, ListView):
    # login_url = "/login/"  # Укажи свой путь к странице логина
    #def get_queryset(self):
        # queryset = LearningCourse.objects.order_by('-title')
        # queryset = LearningCourse.objects.filter(level__contains="B")
        # queryset = LearningCourse.objects.filter(title__endswith="ADVANCED")
    model = LearningCourse
    template_name = 'employee_learning/course_list.html'
    context_object_name = 'course_object_list'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = timezone.now()
        return context


class CourseDetail(LoginRequiredMixin, DetailView):
    model = LearningCourse
    template_name = 'employee_learning/course_detail.html'
    context_object_name = 'course_object'


class CourseCreate(LoginRequiredMixin, CreateView):
    model = LearningCourse
    template_name = 'employee_learning/course_create.html'
    fields = ('title', 'level', 'employee')
    success_url = reverse_lazy('course_list')

class CourseUpdate(LoginRequiredMixin, UpdateView):
    model = LearningCourse
    template_name = 'employee_learning/course_update.html'
    fields = ('title', 'level', 'employee')
    success_url = reverse_lazy('course_list')


class CourseDelete(LoginRequiredMixin, DeleteView):
    model = LearningCourse
    template_name = 'employee_learning/course_delete.html'
    success_url = reverse_lazy('course_list')


class Index(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = timezone.now()
        return context

test_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView

# Create your views here.

def function_view_test(request):
    return HttpResponse("<h1>Hello, World! Function-based View Tes</h1>")

class ClassViewTest(TemplateView):
    template_name = "test.html"

user_profile/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Employee Learning</title>
    {% include 'base/css_link.html' %}
  </head>
  <body>
    {% include 'base/navbar.html' %}
    {% block body %}
        <p syle="font-style: italic">Insert body contents here</p>
    {% endblock %}
    {% include 'base/footer.html' %}
  </body>
</html>

templates/base/css_link.html
{% load static %}
{% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@materializecss/materialize@2.1.0/dist/css/materialize.min.css"> {% endcomment %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">

templates/base/footer.html
<h6 class="text-center text-muted mt-5" style="font-size:.8rem;">2025 Employee Learning</h6>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> 

templates/base/navbar.html
{% load static %}
{% load account %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Training Registration</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav"> <!-- Исправлено на collapse -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'course_list' %}">List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'course_create' %}">Create</a>
        </li>
      </ul>
        <!-- Если пользователь вошел -->
      {% if user.is_authenticated %}
      <ul class="navbar-nav ms-auto align-items-center">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'images/icon.svg' %}" width="30px" class="me-2">
            <span class="fw-bold">{% user_display user %}</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{% url 'account_email' %}">Change E-mail</a></li>
            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign Out</a></li>
          </ul>
        </li>
      </ul>
      {% else %}
      <!-- Если пользователь не вошел -->
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

templates/employee_learning/course_create.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container w-50" style="min-width:300px; max_width:500px;">
        <h1 class="text-center m-5"><img src="{% static 'images/pen.png' %}" width="50px">CREATE</h1>
        <form  method='post'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class='btn btn-primary d-block mx-auto'>Save</button>
        </form>
    </div>
{% endblock body %}

templates/employee_learning/course_delete.html
{% extends "base/base.html" %}
{% block body %}
<div class="container text-center">
    <h1 class="text-center m-5">DELETE Page</h1>
    <from method='post'>
        {% csrf_token %}
        <p class="text-center bg-danger p-0 d-block w-50 mx-auto">Are you sure you want to delete {{ object }}?</p>
        <button type='submit' class='btn btn-danger '>Corfirm</button>
    </form>
</div>
{% endblock body %}

templates/employee_learning/course_detail.html
{% extends "base/base.html" %}
{% block body %}
    <div class="container text-center">
        <h1 class="text-center m-5">DETAIL page</h1>
        <p class="text-muted mt-3 mb-0">Course Title: {{ course_object.title }}
        <p class="text-muted mt-3 mb-0">LEVEL: {{ object.get_level_display }}
        <p class="text-muted mt-3 mb-0">Assigned Employees : </p>
        {% for emp in object.employee.all %}
            <p class="mb-0">{{emp.name}}: {{emp.division}}</p>
        {% endfor %}
        <a href="{% url 'course_update' object.pk %}" class='btn btn-warning m-3'>UPDATE</a>
        <a href="{% url 'course_delete' object.pk %}" class='btn btn-danger m-3'>DELETE</a>
    </div>
{% endblock body %}

templates/employee_learning/course_list.html
{% extends "base/base.html" %}
{% block body %}
    <div class="conteiner text-center">
        <h1 class="text-center mt-5">LIST Page</h1>
        <p class="text-muted text-center mb-5">As of {{today}}</p>
        {% for course in object_list %}
            <div class="card m-1 d-inline-flex" style="width: 18rem; height:10rem;">
                <div class="card-body">
                <h5 class="card-title h-50">{{ course.title|upper }}</h5>
                <p class="card-text">{{ course.get_level_display }}</p>
                <a href="{% url 'course_detail' course.pk %}" class='btn btn-primary p-0 d-block w-50 mx-auto' style='height:1.2rem; font-size:.8rem;'>Go Detail</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/employee_learning/course_update.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container w-50", stule="min-width:300px; max-width:500px;">
        <h1 class="container text-center">UPDATE Page</h1>
        <form method='post'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class='btn btn-warning d-block mx-auto'>Update</button>
        </from>
    </div>
{% endblock body %}

templates/index.html
{% extends 'base/base.html' %}
{% block body %}
<div class="container text-center">
    <h1 class="text-center mt-5">Digital Training Registration</h1>
    <p class="text-muted text-center mb-5">As of {{ today }}</p>
    <a href="{% url 'course_list' %}" class="btn btn-primary m-3">View Registered Programs</a>
    <a href="{% url 'course_create' %}" class="btn btn-primary m-3">Create a New Program</a>
</div>
{% endblock %}

templates/test.html
<h1>Hello, {{ user.username|upper }}! Class-based View Test</h1>